USE [PetRegister]
GO
DECLARE @date date = GETUTCDATE();
DECLARE @yourName varchar(100) = 'Catalina Morera';

INSERT INTO [dbo].[Provincia] VALUES(1,'SAN JOSE',@yourName,@date, @date)
INSERT INTO [dbo].[Provincia] VALUES(2,'ALAJUELA',@yourName,@date, @date)
INSERT INTO [dbo].[Provincia] VALUES(3,'CARTAGO',@yourName,@date, @date)
INSERT INTO [dbo].[Provincia] VALUES(4,'HEREDIA',@yourName,@date, @date)
INSERT INTO [dbo].[Provincia] VALUES(5,'GUANACASTE',@yourName,@date, @date)
INSERT INTO [dbo].[Provincia] VALUES(6,'PUNTARENAS',@yourName,@date, @date)
INSERT INTO [dbo].[Provincia] VALUES(7,'LIMON',@yourName,@date, @date)

INSERT INTO [dbo].[Canton] VALUES (1,1,'SAN JOSE',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (2,1,'ESCAZU',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (3,1,'DESAMPARADOS',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (4,1,'PURISCAL',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (5,1,'TARRAZU',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (6,1,'ASERRI',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (7,1,'MORA',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (8,1,'GOICOECHEA',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (9,1,'SANTA ANA',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (10,1,'ALAJUELITA',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (11,1,'CORONADO',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (12,1,'ACOSTA',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (13,1,'TIBAS',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (14,1,'MORAVIA',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (15,1,'MONTES DE OCA',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (16,1,'TURRUBARES',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (17,1,'DOTA',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (18,1,'CURRIDABAT',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (19,1,'PEREZ ZELEDON',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (20,1,'LEON CORTES',@yourName,@date, @date)

INSERT INTO [dbo].[Canton] VALUES (1,2,'ALAJUELA',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (2,2,'SAN RAMON',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (3,2,'GRECIA',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (4,2,'SAN MATEO',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (5,2,'ATENAS',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (6,2,'NARANJO',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (7,2,'PALMARES',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (8,2,'POAS',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (9,2,'OROTINA',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (10,2,'SAN CARLOS',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (11,2,'ALFARO RUIZ',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (12,2,'VALVERDE VEGA',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (13,2,'UPALA',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (14,2,'LOS CHILES',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (15,2,'GUATUSO',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (16,2,'RIO CUARTO',@yourName,@date, @date)

INSERT INTO [dbo].[Canton] VALUES (1,3,'CARTAGO',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (2,3,'PARAISO',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (3,3,'LA UNION',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (4,3,'JIMENEZ',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (5,3,'TURRIALBA',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (6,3,'ALVARADO',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (7,3,'OREAMUNO',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (8,3,'EL GUARCO',@yourName,@date, @date)

INSERT INTO [dbo].[Canton] VALUES (1,4,'HEREDIA',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (2,4,'BARVA',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (3,4,'SANTO DOMINGO',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (4,4,'SANTA BARBARA',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (5,4,'SAN RAFAEL',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (6,4,'SAN ISIDRO',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (7,4,'BELEN',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (8,4,'FLORES',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (9,4,'SAN PABLO',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (10,4,'SARAPIQUI',@yourName,@date, @date)

INSERT INTO [dbo].[Canton] VALUES (1,5,'LIBERIA',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (2,5,'NICOYA',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (3,5,'SANTA CRUZ',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (4,5,'BAGACES',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (5,5,'CARRILLO',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (6,5,'CAÑAS',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (7,5,'ABANGARES',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (8,5,'TILARAN',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (9,5,'NANDAYURE',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (10,5,'LA CRUZ',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (11,5,'HOJANCHA',@yourName,@date, @date)

INSERT INTO [dbo].[Canton] VALUES (1,6,'PUNTARENAS',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (2,6,'ESPARZA',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (3,6,'BUENOS AIRES',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (4,6,'MONTES DE ORO',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (5,6,'OSA',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (6,6,'AGUIRRE',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (7,6,'GOLFITO',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (8,6,'COTO BRUS',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (9,6,'PARRITA',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (10,6,'CORREDORES',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (11,6,'GARABITO',@yourName,@date, @date)

INSERT INTO [dbo].[Canton] VALUES (1,7,'LIMON',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (2,7,'POCOCI',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (3,7,'SIQUIRRES',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (4,7,'TALAMANCA',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (5,7,'MATINA',@yourName,@date, @date)
INSERT INTO [dbo].[Canton] VALUES (6,7,'GUACIMO',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,1,1,'Carmen',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,1,1,'Merced',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,1,1,'Hospital',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,1,1,'Catedral',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,1,1,'Zapote',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,1,1,'San Francisco de Dos Ríos',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (7,1,1,'Uruca',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (8,1,1,'Mata Redonda',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (9,1,1,'Pavas',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (10,1,1,'Hatillo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (11,1,1,'San Sebastián',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,2,1,'Escazú',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,2,1,'San Antonio',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,2,1,'San Rafael',@yourName,@date, @date)


INSERT INTO [dbo].[Distrito] VALUES (1,3,1,'Desamparados',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,3,1,'San Miguel',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,3,1,'San Juan de Dios',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,3,1,'San Rafael Arriba',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,3,1,'San Antonio',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,3,1,'Frailes',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (7,3,1,'Patarrá',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (8,3,1,'San Cristóbal',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (9,3,1,'Rosario',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (10,3,1,'Damas',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (11,3,1,'San Rafael Abajo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (12,3,1,'Gravilias',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (13,3,1,'Los Guido',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,4,1,'Santiago',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,4,1,'Mercedes Sur',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,4,1,'Barbacoas',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,4,1,'Grifo Alto',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,4,1,'San Rafael',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,4,1,'Candelarita',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (7,4,1,'Desamparaditos',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (8,4,1,'San Antonio',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (9,4,1,'Chires',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (10,4,1,'La Cangreja',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,5,1,'San Marcos',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,5,1,'San Lorenzo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,5,1,'San Carlos',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,6,1,'Aserrí',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,6,1,'Tarbaca o Praga',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,6,1,'Vuelta de Jorco',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,6,1,'San Gabriel',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,6,1,'La Legua',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,6,1,'Monterrey',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (7,6,1,'Salitrillos',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,7,1,'Ciudad Colón',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,7,1,'Guayabo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,7,1,'Tabarcia',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,7,1,'Piedras Negras',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,7,1,'Picagres',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,7,1,'Jaris',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (7,7,1,'Quitirrisi',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,8,1,'Guadalupe',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,8,1,'San Francisco',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,8,1,'Calle Blancos',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,8,1,'Mata de Plátano',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,8,1,'Ipís',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,8,1,'Rancho Redondo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (7,8,1,'Purral',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,9,1,'Santa Ana',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,9,1,'Salitral',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,9,1,'Pozos o Concepción',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,9,1,'Uruca o San Joaquín',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,9,1,'Piedades',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,9,1,'Brasil',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (1,1,10,'Alajuelita',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,1,10,'San Josecito',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,1,10,'San Antonio',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,1,10,'Concepción',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,1,10,'San Felipe',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (1,1,11,'San Isidro',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,1,11,'San Rafael',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,1,11,'Dulce Nombre o Jesús',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,1,11,'Patalillo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,1,11,'Cascajal',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,1,12,'San Ignacio',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,1,12,'Guaitil',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,1,12,'Palmichal',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,1,12,'Cangrejal',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,1,12,'Sabanillas',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,1,13,'San Juan',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,1,13,'Cinco Esquinas',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,1,13,'Anselmo Llorente',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,1,13,'León XIII',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,1,13,'Colima',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,1,14,'San Vicente',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,1,14,'San Jerónimo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,1,14,'La Trinidad',@yourName,@date, @date)


INSERT INTO [dbo].[Distrito] VALUES (1,1,15,'San Pedro',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,1,15,'Sabanilla',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,1,15,'Mercedes o Betania',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,1,15,'San Rafael',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,1,16,'San Pablo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,1,16,'San Pedro',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,1,16,'San Juan de Mata',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,1,16,'San Luis',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,1,16,'Carara',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,1,17,'Santa María',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,1,17,'Jardín',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,1,17,'Copey',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,1,18,'Curridabat',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,1,18,'Granadilla',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,1,18,'Sánchez',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,1,18,'Tirrases',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,1,19,'San Isidro de El General',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,1,19,'General',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,1,19,'Daniel Flores',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,1,19,'Rivas',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,1,19,'San Pedro',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,1,19,'Platanares',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (7,1,19,'Pejibaye',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (8,1,19,'Cajón o Carmen',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (9,1,19,'Barú',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (10,1,19,'Río Nuevo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (11,1,19,'Páramo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (12,1,19,'La Amistad',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,1,20,'San Pablo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,1,20,'San Andrés',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,1,20,'Llano Bonito',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,1,20,'San Isidro',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,1,20,'Santa Cruz',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,1,20,'San Antonio',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,1,2,'Alajuela',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,1,2,'San José',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,1,2,'Carrizal',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,1,2,'San Antonio',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,1,2,'Guácima',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,1,2,'San Isidro',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (7,1,2,'Sabanilla',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (8,1,2,'San Rafael',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (9,1,2,'Río Segundo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (10,1,2,'Desamparados',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (11,1,2,'Turrucares',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (12,1,2,'Tambor',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (13,1,2,'La Garita',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (14,1,2,'Sarapiquí',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,2,2,'San Ramón',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,2,2,'Santiago',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,2,2,'San Juan',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,2,2,'Piedades Norte',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,2,2,'Piedades Sur',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,2,2,'San Rafael',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (7,2,2,'San Isidro',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (8,2,2,'Angeles',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (9,2,2,'Alfaro',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (10,2,2,'Volio',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (11,2,2,'Concepción',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (12,2,2,'Zapotal',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (13,2,2,'San Isidro de Peñas Blancas',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (14,2,2,'San Lorenzo',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,3,2,'Grecia',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,3,2,'San Isidro',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,3,2,'San José',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,3,2,'San Roque',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,3,2,'Tacares',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,3,2,'Puente Piedra',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (7,3,2,'Bolívar',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,4,2,'San Mateo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,4,2,'Desmonte',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,4,2,'Jesús María',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,4,2,'Labrador',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,5,2,'Atenas',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,5,2,'Jesús',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,5,2,'Mercedes',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,5,2,'San Isidro',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,5,2,'Concepción',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,5,2,'San José',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (7,5,2,'Santa Eulalia',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (8,5,2,'Escobal',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,6,2,'Naranjo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,6,2,'San Miguel',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,6,2,'San José',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,6,2,'Cirrí Sur',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,6,2,'San Jerónimo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,6,2,'San Juan',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (7,6,2,'Rosario',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,7,2,'Palmares',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,7,2,'Zaragoza',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,7,2,'Buenos Aires',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,7,2,'Santiago',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,7,2,'Candelaria',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,7,2,'Esquipulas',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (7,7,2,'La Granja',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,8,2,'San Pedro',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,8,2,'San Juan',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,8,2,'San Rafael',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,8,2,'Carrillos',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,8,2,'Sabana Redonda',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,9,2,'Orotina',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,9,2,'Mastate',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,9,2,'Hacienda Vieja',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,9,2,'Coyolar',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,9,2,'Ceiba',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,2,10,'Quesada',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,2,10,'Florencia',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,2,10,'Buenavista',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,2,10,'Aguas Zarcas',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,2,10,'Venecia',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,2,10,'Pital',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (7,2,10,'Fortuna',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (8,2,10,'Tigra',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (9,2,10,'Palmera',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (10,2,10,'Venado',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (11,2,10,'Cutris',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (12,2,10,'Monterrey',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (13,2,10,'Pocosol',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,2,11,'Zarcero',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,2,11,'Laguna',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,2,11,'Tapezco',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,2,11,'Guadalupe',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,2,11,'Palmira',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,2,11,'Zapote',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (7,2,11,'Brisas',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,2,12,'Sarchí Norte',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,2,12,'Sarchí Sur',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,2,12,'Toro Amarillo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,2,12,'San Pedro',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,2,12,'Rodríguez',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,2,13,'Upala',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,2,13,'Aguas Claras',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,2,13,'San José o Pizote',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,2,13,'Bijagua',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,2,13,'Delicias',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,2,13,'Dos Ríos',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (7,2,13,'Yolillal',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (8,2,13,'Canalete',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,2,14,'Los Chiles',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,2,14,'Caño Negro',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,2,14,'Amparo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,2,14,'San Jorge',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,2,15,'San Rafael',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,2,15,'Buenavista',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,2,15,'Cote',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,2,15,'Katira',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,2,16,'Rio Cuarto',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,1,3,'Oriental',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,1,3,'Occidental',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,1,3,'Carmen',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,1,3,'San Nicolás',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,1,3,'Aguacaliente  (San Francisco,@yourName,@date, @date)',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,1,3,'Guadalupe  (Arenilla,@yourName,@date, @date)',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (7,1,3,'Corralillo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (8,1,3,'Tierra Blanca',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (9,1,3,'Dulce Nombre',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (10,1,3,'Llano Grande',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (11,1,3,'Quebradilla',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (1,2,3,'Paraíso',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,2,3,'Santiago',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,2,3,'Orosi',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,2,3,'Cachí',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,2,3,'Llanos de Sta Lucia',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,3,3,'Tres Ríos',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,3,3,'San Diego',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,3,3,'San Juan',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,3,3,'San Rafael',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,3,3,'Concepción',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,3,3,'Dulce Nombre',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (7,3,3,'San Ramón',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (8,3,3,'Río Azul',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,4,3,'Juan Viñas',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,4,3,'Tucurrique',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,4,3,'Pejibaye',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,5,3,'Turrialba',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,5,3,'La Suiza',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,5,3,'Peralta',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,5,3,'Santa Cruz',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,5,3,'Santa Teresita',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,5,3,'Pavones',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (7,5,3,'Tuis',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (8,5,3,'Tayutic',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (9,5,3,'Santa Rosa',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (10,5,3,'Tres Equis',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (11,5,3,'La Isabel',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (12,5,3,'Chirripo',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,6,3,'Pacayas',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,6,3,'Cervantes',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,6,3,'Capellades',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,7,3,'San Rafael',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,7,3,'Cot',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,7,3,'Potrero Cerrado',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,7,3,'Cipreses',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,7,3,'Santa Rosa',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,8,3,'El Tejar',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,8,3,'San Isidro',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,8,3,'Tobosi',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,8,3,'Patio de Agua',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,1,4,'Heredia',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,1,4,'Mercedes',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,1,4,'San Francisco',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,1,4,'Ulloa',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,1,4,'Vara Blanca',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,2,4,'Barva',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,2,4,'San Pedro',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,2,4,'San Pablo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,2,4,'San Roque',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,2,4,'Santa Lucía',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,2,4,'San José de la Montaña',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,3,4,'Santo Domingo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,3,4,'San Vicente',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,3,4,'San Miguel',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,3,4,'Paracito',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,3,4,'Santo Tomás',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,3,4,'Santa Rosa',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (7,3,4,'Tures',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (8,3,4,'Pará',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,4,4,'Santa Bárbara',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,4,4,'San Pedro',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,4,4,'San Juan',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,4,4,'Jesús',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,4,4,'Santo Domingo del Roble',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,4,4,'Puraba',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,5,4,'San Rafael',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,5,4,'San Josecito',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,5,4,'Santiago',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,5,4,'Angeles',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,5,4,'Concepción',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,6,4,'San Isidro',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,6,4,'San José',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,6,4,'Concepción',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,6,4,'San Francisco',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,7,4,'San Antonio',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,7,4,'La Rivera',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,7,4,'Asunción',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,8,4,'San Joaquín',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,8,4,'Barrantes',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,8,4,'Llorente',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,9,4,'San Pablo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,9,4,'Rincon de Sabanilla',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,4,10,'Puerto Viejo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,4,10,'La Virgen',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,4,10,'Horquetas',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,4,10,'Llanuras del Gaspar',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,4,10,'Cureña',@yourName,@date, @date)



INSERT INTO [dbo].[Distrito] VALUES (1,1,5,'Liberia',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,1,5,'Cañas Dulces',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,1,5,'Mayorga',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,1,5,'Nacascolo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,1,5,'Curubande',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,2,5,'Nicoya',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,2,5,'Mansión',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,2,5,'San Antonio',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,2,5,'Quebrada Honda',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,2,5,'Sámara',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,2,5,'Nosara',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (7,2,5,'Belén de Nosarita',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,3,5,'Santa Cruz',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,3,5,'Bolsón',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,3,5,'Veintisiete de Abril',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,3,5,'Tempate',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,3,5,'Cartagena',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,3,5,'Cuajiniquil',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (7,3,5,'Diriá',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (8,3,5,'Cabo Velas',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (9,3,5,'Tamarindo',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,4,5,'Bagaces',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,4,5,'Fortuna',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,4,5,'Mogote',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,4,5,'Río Naranjo',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,5,5,'Filadelfia',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,5,5,'Palmira',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,5,5,'Sardinal',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,5,5,'Belén',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,6,5,'Cañas',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,6,5,'Palmira',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,6,5,'San Miguel',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,6,5,'Bebedero',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,6,5,'Porozal',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,7,5,'Juntas',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,7,5,'Sierra',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,7,5,'San Juan',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,7,5,'Colorado',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,8,5,'Tilarán',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,8,5,'Quebrada Grande',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,8,5,'Tronadora',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,8,5,'Santa Rosa',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,8,5,'Líbano',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,8,5,'Tierras Morenas',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (7,8,5,'Arenal',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,9,5,'Carmona',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,9,5,'Santa Rita',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,9,5,'Zapotal',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,9,5,'San Pablo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,9,5,'Porvenir',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,9,5,'Bejuco',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,5,10,'La Cruz',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,5,10,'Santa Cecilia',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,5,10,'Garita',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,5,10,'Santa Elena',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,5,11,'Hojancha',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,5,11,'Monte Romo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,5,11,'Puerto Carrillo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,5,11,'Huacas',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,5,11,'Matambú',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,1,6,'Puntarenas',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,1,6,'Pitahaya',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,1,6,'Chomes',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,1,6,'Lepanto',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,1,6,'Paquera',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,1,6,'Manzanillo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (7,1,6,'Guacimal',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (8,1,6,'Barranca',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (9,1,6,'Monte Verde',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (10,1,6,'Isla del Coco',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (11,1,6,'Cóbano',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (12,1,6,'Chacarita',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (13,1,6,'Chira (Isla,@yourName,@date, @date)',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (14,1,6,'Acapulco',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (15,1,6,'El Roble',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (16,1,6,'Arancibia',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,2,6,'Espíritu Santo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,2,6,'San Juan Grande',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,2,6,'Macacona',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,2,6,'San Rafael',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,2,6,'San Jerónimo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,2,6,'Caldera',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,3,6,'Buenos Aires',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,3,6,'Volcán',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,3,6,'Potrero Grande',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,3,6,'Boruca',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,3,6,'Pilas',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,3,6,'Colinas o Bajo de Maíz',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (7,3,6,'Chánguena',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (8,3,6,'Biolley',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (9,3,6,'Brunka',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,4,6,'Miramar',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,4,6,'Unión',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,4,6,'San Isidro',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,5,6,'Ciudad Cortés',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,5,6,'Palmar',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,5,6,'Sierpe',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,5,6,'Bahía Ballena',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,5,6,'Piedras Blancas',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,5,6,'Bahia Drake',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,6,6,'Quepos',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,6,6,'Savegre',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,6,6,'Naranjito',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,7,6,'Golfito',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,7,6,'Puerto Jiménez',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,7,6,'Guaycará',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,7,6,'Pavones o Villa Conte',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,8,6,'San Vito',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,8,6,'Sabalito',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,8,6,'Agua Buena',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,8,6,'Limoncito',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,8,6,'Pittier',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,8,6,'Gutierrez Brown',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,9,6,'Parrita',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,6,10,'Corredores',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,6,10,'La Cuesta',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,6,10,'Paso Canoas',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,6,10,'Laurel',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,6,11,'Jacó',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,6,11,'Tárcoles',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,1,7,'Limón',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,1,7,'Valle  La Estrella',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,1,7,'Río Blanco',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,1,7,'Matama',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,2,7,'Guápiles',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,2,7,'Jiménez',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,2,7,'Rita',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,2,7,'Roxana',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,2,7,'Cariari',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,2,7,'Colorado',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (7,2,7,'La Colonia',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,3,7,'Siquirres',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,3,7,'Pacuarito',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,3,7,'Florida',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,3,7,'Germania',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,3,7,'Cairo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (6,3,7,'Alegría',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,4,7,'Bratsi',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,4,7,'Sixaola',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,4,7,'Cahuita',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,4,7,'Telire',@yourName,@date, @date)

INSERT INTO [dbo].[Distrito] VALUES (1,5,7,'Matina',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,5,7,'Batán',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,5,7,'Carrandí',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (1,6,7,'Guácimo',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (2,6,7,'Mercedes',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (3,6,7,'Pocora',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (4,6,7,'Río Jiménez',@yourName,@date, @date)
INSERT INTO [dbo].[Distrito] VALUES (5,6,7,'Duacarí',@yourName,@date, @date)



INSERT INTO [dbo].[Categories] VALUES ('Cat','The cat (Felis catus) is a domestic species of small carnivorous mammal. ','https://thumbs.dreamstime.com/z/animales-de-animal-dom%C3%A9stico-de-la-historieta-44759097.jpg',@yourName,@date, @date)
INSERT INTO [dbo].[Categories] VALUES ('Dog','The dog or domestic dog (Canis familiaris[4][5] or Canis lupus familiaris[5]) is a domesticated descendant of the wolf, and is characterized by an upturning tail.','https://thumbs.dreamstime.com/z/animales-de-animal-dom%C3%A9stico-de-la-historieta-44759097.jpg',@yourName,@date, @date)
INSERT INTO [dbo].[Categories] VALUES ('Birds','Birds are a group of warm-blooded vertebrates constituting the class Aves (/ˈeɪviːz/), characterised by feathers, toothless beaked jaws, the laying of hard-shelled eggs, a high metabolic rate, a four-chambered heart, and a strong yet lightweight skeleton. ','https://thumbs.dreamstime.com/z/animales-de-animal-dom%C3%A9stico-de-la-historieta-44759097.jpg',@yourName,@date, @date)
INSERT INTO [dbo].[Categories] VALUES ('Rodent','Rodents are mammals of the order Rodentia (/roʊˈdɛnʃə/), which are characterized by a single pair of continuously growing incisors in each of the upper and lower jaws.','https://thumbs.dreamstime.com/z/animales-de-animal-dom%C3%A9stico-de-la-historieta-44759097.jpg',@yourName,@date, @date)
INSERT INTO [dbo].[Categories] VALUES ('Reptile','Reptiles, as most commonly defined, are the animals in the class Reptilia (/rɛpˈtɪliə/), a paraphyletic grouping comprising all sauropsid amniotes except Aves (birds).[1] Living reptiles comprise turtles, crocodilians, squamates (lizards and snakes) and rhynchocephalians (tuatara).','https://thumbs.dreamstime.com/z/animales-de-animal-dom%C3%A9stico-de-la-historieta-44759097.jpg',@yourName,@date, @date)
INSERT INTO [dbo].[Categories] VALUES ('Fish','Fish are aquatic, craniate, gill-bearing animals that lack limbs with digits. Included in this definition are the living hagfish, lampreys, and cartilaginous and bony fish as well as various extinct related groups. Around 99% of living fish species are ray-finned fish, belonging to the class Actinopterygii, with over 95% belonging to the teleost subgrouping','https://thumbs.dreamstime.com/z/animales-de-animal-dom%C3%A9stico-de-la-historieta-44759097.jpg',@yourName,@date, @date)


INSERT INTO [dbo].[Owner] VALUES('106760742','Morera','Catalina','','','',1,1,1,'89786721','89786721','2008-11-11 13:23:44','https://previp-of-young-people-vector-illustration-design.jpg',@yourName,@date, @date)
INSERT INTO [dbo].[Owner] VALUES('206760742','Granados','Ingrid','','','',1,1,1,'89786721','89786721','2008-11-11 13:23:44','https://previp-of-young-people-vector-illustration-design.jpg',@yourName,@date, @date)
INSERT INTO [dbo].[Owner] VALUES('206760742','Morera','David','','','',1,1,1,'89786721','89786721','2008-11-11 13:23:44','https://previp-of-young-people-vector-illustration-design.jpg',@yourName,@date, @date)
INSERT INTO [dbo].[Owner] VALUES('206760742','Morera','Alonso','','','',1,1,1,'89786721','89786721','2008-11-11 13:23:44','https://previp-of-young-people-vector-illustration-design.jpg',@yourName,@date, @date)
INSERT INTO [dbo].[Owner] VALUES('306760742','Granados','Grace','','','',1,1,1,'89786721','89786721','2008-11-11 13:23:44','https://previp-of-young-people-vector-illustration-design.jpg',@yourName,@date, @date)
INSERT INTO [dbo].[Owner] VALUES('406760742','Granados','Anabelle','','','',1,1,1,'89786721','89786721','2008-11-11 13:23:44','https://previp-of-young-people-vector-illustration-design.jpg',@yourName,@date, @date)
INSERT INTO [dbo].[Owner] VALUES('506760742','Granados','Leda','','','',1,1,1,'89786721','89786721','2008-11-11 13:23:44','https://previp-of-young-people-vector-illustration-design.jpg',@yourName,@date, @date)
INSERT INTO [dbo].[Owner] VALUES('606760742','Granados','Lorena','','','',1,1,1,'89786721','89786721','2008-11-11 13:23:44','https://previp-of-young-people-vector-illustration-design.jpg',@yourName,@date, @date)
INSERT INTO [dbo].[Owner] VALUES('706760742','Granados','Farhana','','','',1,1,1,'89786721','89786721','2008-11-11 13:23:44','https://previp-of-young-people-vector-illustration-design.jpg',@yourName,@date, @date)
INSERT INTO [dbo].[Owner] VALUES('806760742','Mendez','Krista','','','',1,1,1,'89786721','89786721','2008-11-11 13:23:44','https://previp-of-young-people-vector-illustration-design.jpg',@yourName,@date, @date)
INSERT INTO [dbo].[Owner] VALUES('906760742','Morera','Saul','','','',1,1,1,'89786721','89786721','2008-11-11 13:23:44','https://previp-of-young-people-vector-illustration-design.jpg',@yourName,@date, @date)
INSERT INTO [dbo].[Owner] VALUES('006760742','Morera','Irene','','','',1,1,1,'89786721','89786721','2008-11-11 13:23:44','https://previp-of-young-people-vector-illustration-design.jpg',@yourName,@date, @date)
INSERT INTO [dbo].[Owner] VALUES('006760742','Cartin','Paola','','','',1,1,1,'89786721','89786721','2008-11-11 13:23:44','https://previp-of-young-people-vector-illustration-design.jpg',@yourName,@date, @date)

INSERT INTO [dbo].[Pet] VALUES('Coral',1.5,0.8,'San Ramon','White',2,1,'2008-11-11 13:23:44','https://i.pinimg.com/236x/a1/44/c6/a144c64bd6c6db9e438842f5412e81d9.jpg',@yourName,@date, @date)
INSERT INTO [dbo].[Pet] VALUES('Eva',1.5,0.8,'San Ramon','White',2,1,'2008-11-11 13:23:44','https://i.pinimg.com/236x/a1/44/c6/a144c64bd6c6db9e438842f5412e81d9.jpg',@yourName,@date, @date)
INSERT INTO [dbo].[Pet] VALUES('Luna',1.5,0.8,'San Ramon','White',2,1,'2008-11-11 13:23:44','https://i.pinimg.com/236x/a1/44/c6/a144c64bd6c6db9e438842f5412e81d9.jpg',@yourName,@date, @date)
INSERT INTO [dbo].[Pet] VALUES('Aurora',1.5,0.8,'San Ramon','White',2,1,'2008-11-11 13:23:44','https://i.pinimg.com/236x/a1/44/c6/a144c64bd6c6db9e438842f5412e81d9.jpg',@yourName,@date, @date)
INSERT INTO [dbo].[Pet] VALUES('Estela',1.5,0.8,'San Ramon','White',2,1,'2008-11-11 13:23:44','https://i.pinimg.com/236x/a1/44/c6/a144c64bd6c6db9e438842f5412e81d9.jpg',@yourName,@date, @date)
INSERT INTO [dbo].[Pet] VALUES('Dino',1.5,0.8,'San Ramon','White',2,1,'2008-11-11 13:23:44','https://i.pinimg.com/236x/a1/44/c6/a144c64bd6c6db9e438842f5412e81d9.jpg',@yourName,@date, @date)
INSERT INTO [dbo].[Pet] VALUES('Dino',1.5,0.8,'San Ramon','White',2,1,'2008-11-11 13:23:44','https://i.pinimg.com/236x/a1/44/c6/a144c64bd6c6db9e438842f5412e81d9.jpg',@yourName,@date, @date)